### ISSUE TITLE
How do I use the script??

### ISSUE THREAD

**Issue by fvbatistoni** [alirezaevil81/freepik-geter#1]
I have installed as you said.
I've created a **index.php** page inside **/src**  folder, but it did not worked
I see this message: Fatal error: Uncaught Error: Class "FreepikAPi" not found in E:\xampp\htdocs\freepik-geter\src\index.php:7 Stack trace: #0 {main} thrown in E:\xampp\htdocs\freepik-geter\src\index.php on line 7
<?php
// https://github.com/alirezaevil81/freepik-geter?tab=readme-ov-file
require_once '../vendor/autoload.php';
require_once 'FreepikAPi.php';

$freepik = new FreepikAPi("FPSX3aa254489642432b8858b28956249719");

$freepik->resources(1, 'car', 4, 'random')->orientation(true)->quickEdit(false)->choice(false)->contentType(true)->people(true,false,4)->request()->showResources();
$freepik->resourceDownloadByFormat('13240356', 'jpg')->request()->getResourceByFormat('img');
?>

**Comment by alirezaevil81** [comment]
use FreepikApi class up your php code
